docker-compose.yml

The "always" restart policy "always restarts the container until its
removal." This means that that one could explicitly stop a container and
then restart one's computer, and the container would still be running
after the reboot.
Given that the Compose file in this repository appears to be used for
development and QA purposes, this is a bit painful. I'd rather not have
dev or qa tooling making my computer do things even after reboot.

Change restart policy to on-failure

---

api/controllers/config_manager_controller.go
application/config_manager_service.go
config/config.go
deploy/clowdapp.yml
docker-compose.yml
domain/cloud_connector.go
infrastructure/container.go
infrastructure/persistence/cloud_connector_repository.go
infrastructure/persistence/cloud_connector_repository_test.go
infrastructure/persistence/dispatcher_repository.go
infrastructure/persistence/dispatcher_repository_test.go
utils/http_client.go

This PR allows config-manager to retrieve a list of connected clients for the requesting account from the cloud-connector service. Eventually these clients will be retrieved from HBI, but in the meantime we can use cloud-connector to get the currently connected clients for dispatching work to the playbook-dispatcher. 
Another PR will follow that includes the inventory connector and a refactor to allow for easier swapping of the "client/host retriever".

Adding cloud-connector integration

---

application/config_manager_service.mock.go
domain/config_manager.go
domain/message/inventory.go
infrastructure/kafka/kafka.go
inventory-consumer/handler.go
inventory-consumer/handler_test.go
inventory-consumer/main.go

This is a bit of a mess, but this PR enables config-manager to apply the account's current service enablement config to any newly connected clients that are reported to inventory via cloud-connector. Currently a playbook will be supplied to a host if it has been either recently created or updated.
Once config-manager is updating hosts in inventory we can utilize the rhc_config_state system-profile field and only supply a playbook when a client is recently created or out of date (to avoid unnecessary work on simple disconnects). 
A minimal mock for the ConfigManagerService was added for testing purposes, and will be expanded on as needed.

Inventory consumer

---

api/controllers/config_manager_controller.go

Quick fix to enable the rhc client to run the playbook included in the http response directly

Adding playbook content to json response as string instead of interface

---

application/generator.go
application/generator_test.go

This isn't strictly necessary as it works fine without the check, but it does make it clearer that the service enablement state can include services that don't require playbooks. For example remediations does not get set up or removed via a playbook, but an org admin can disable playbook execution via the service enablement dashboard. 
The generator tests are poorly done - they need to be updated

Checking existence of play before adding it to the playbook

---

api/controllers/config_manager_controller.go
api/controllers/spec.gen.go
api/controllers/types.gen.go
application/config_manager_service.go
domain/state_archive.go
infrastructure/persistence/state_archive_repository.go
schema/api.spec.yaml

@Ichimonji10 This PR changes the response format when performing a GET on /states. The array that used to be returned is now located in the "results" field of the response, and pagination metadata was also added.

Adding pagination metadata to /states response. Adding preview endpoint

---

infrastructure/container.go
infrastructure/persistence/cloud_connector_repository.go
infrastructure/persistence/dispatcher_repository.go

@Ichimonji10 This should allow the local tests to pass properly while still preserving the mocked clients for unit testing. Let me know if you still see any issues.

Updating connectors to behave correctly when using mocked implementation

---

inventory-consumer/handler.go
inventory-consumer/handler_test.go

This PR updates the inventory consumer to compare the rhc_state_id in system profile to the current state id for the respective account. If the ids match then no work is sent to the client.

Checking state id from inventory before sending message

---

api/controllers/config_manager_controller.go
utils/utils.go
utils/utils_test.go

JIRA: https://issues.redhat.com/browse/RHCLOUD-13763
This change does two things:
1. Check to see if the provided state is the same as the current state - if they're the same don't create a new state change and let the client know
2. If "insights" is disabled make sure the additional services are also disabled - if they aren't don't make any changes and let the client know
@dehort this solution isn't generic enough, but it will be updated once there is more logic built around the services themselves (ie make a distinction between parent/child services to validate the states without specifically calling out 'insights')
Currently it will return a 400 for both of the above cases, but it may also make sense to return a 200 and then the unchanged current state?

Adding additional restrictions when updating service states

---

api/controllers/config_manager_controller.go
api/controllers/spec.gen.go
api/controllers/types.gen.go
application/config_manager_service.go
domain/state_archive.go
infrastructure/persistence/state_archive_repository.go
schema/api.spec.yaml

@Ichimonji10 Not sure if this will break the iqe tests, but this change modifies the response from /states to return the latest state change first (descending order). It also adds the sort_by query parameter
https://issues.redhat.com/browse/RHCLOUD-14084

Adding sorting to state archives

---

api/controllers/config_manager_controller.go

@dehort @rodrigonull This PR aims to resolve the case where RHC connected hosts are ignored due to the host entry in inventory missing the rhc_client_id. This can happen by turning off/on the insights-client causing inventory records to be regenerated without the rhc_client_id being present in the system_profile.
Config-manager will first attempt to gather any connected hosts through inventory, and then record the found rhc_client_ids. It will then also gather connected hosts through cloud-connector and merge the results to ensure no hosts are ignored due to a missing rhc_client_id.

Use both data sources for connected accounts

---

.github/labeler.yml
.github/workflows/label.yml

Add autolabeler for stale template signatures.
This github action will automatically label any PR that changes the templates stored in the config-manager repo.  This will allow the GITHUB slack integration to pick it up and alert the pipeline team whenever a signature needs to be re-signed.
JIRA: https://issues.redhat.com/browse/RHCLOUD-13831

Add autolabeler for stale signatures

---

.gitignore
Makefile
README.md
bonfire_config.yaml
bonfire_deploy.sh

Steps required to deploy config-manager locally using minikube, clowder, and bonfire

Updating docs with clowder deployment info

---

application/config_manager_service.go

This change will remove the step of validating a client's connection status with cloud-connector before dispatching work. It is not necessary to check connections status of a client after retrieving it from inventory since disconnected systems will have been removed from inventory upon disconnect.

removing cloud-connector check

---

README.md

The clouddot URLs are gone. Update them to what I think are the closest
equivalent consoledot URLs.

docs: update clouddot URLs

---

api/controllers/config_manager_controller.go

The context.Value() call was updated to use the persistence.IdentityKey
global variable when finding the context value. Use the same key when
creating the context too.
Fixes: ESSNTL-2707

fix: use global value key when creating context

---

application/config_manager_service.go
infrastructure/kafka/kafka.go

After reading the next message from a kafka reader, handle it in a goroutine rather than on the current thread. This enables multiple messages to be handled simultaneously. If one host is taking a while to install rhc-worker-playbook, it will no longer block the other hosts from being set up.

Handle kafka message concurrently

---

dispatcher-consumer/handler.go
dispatcher-consumer/handler_test.go
domain/message/dispatcher.go
domain/message/inventory.go

This adds back the account field that was removed in commit 1a4f3047665521aba09619ea7b09910fd1eeb38e.
This field can be removed after the completion of [ESSNTL-2529](https://issues.redhat.com/browse/ESSNTL-2529).

refactor: use account and org_id in the kafka handler

---

dispatcher-consumer/handler.go
dispatcher-consumer/handler_test.go
domain/message/dispatcher.go
domain/message/inventory.go

Removes the `account` field as part of [RHCLOUD-20315](https://issues.redhat.com/browse/RHCLOUD-20315)
Field is no longer required as of [ESSNTL-2529](https://issues.redhat.com/browse/ESSNTL-2529)

refactor: remove account field from kafka handler

---

deploy/clowdapp.yml

Add the org-id-populator job to translate empty OrgIDs from AccountIDs in the `profiles` table.

feat: add org-id-populator job

---

go.mod
go.sum
internal/http/v1/router.go

The API route group is validated by the OapiRequestValidator, which
does not accept URLBasePath()+"/openapi.json" as a valid request.
Fixes: ESSNTL-3221

fix: handle openapi.json outside API route group

---

internal/http/v1/openapi.yaml

console.redhat.com/docs/api wants openapi version 3.0.0, not 3.1.x

feat: downgrade the openapi spec version to 3.0.0

---

deploy/clowdapp.yml

Decrease the org-id-populator CJI batch size from 100 to 50. This will hopefully solve issues with the failed translation job in PROD.

fix: decrease the populator batch size to 50

---

CONTRIBUTING.md
infrastructure/persistence/cloudconnector/cloudconnector.go
internal/cmd/inventoryconsumer/cmd.go
internal/host.go
internal/http/v1/handlers.go
internal/util/batch.go
internal/util/batch_test.go
scripts/bonfire.yml

Rewrite the ApplyProfile batch processing code to use a separate
batching function. Instead of running the code synchronously, each batch
is sent to playbook-dispatcher on a groutine. ApplyProfile accepts
a function that is called when the batch receives a response from
playbook-dispatcher.
Fixes: ESSNTL-3238

batch runs to playbook-dispatcher correctly

---

infrastructure/persistence/cloudconnector/cloudconnector_test.go
infrastructure/persistence/dispatcher/dispatcher_test.go
infrastructure/persistence/inventory/inventory_repository_test.go
internal/host.go

The "reporter" field only contains the most recent reporter for a host.
In order to send a state playbook to a host, config-manager needs to
know if it was ever reported by "cloud-connector", rather than if it was
most recently reported. The "per_reporter_staleness" field contains a
map of all reporters for the host, so using the presence or absence of a
key in that map correctly identifies whether a host has ever been
reported by cloud-connector.
Fixes: ESSNTL-3287

fix: use per_reporter_staleness to detect reporter

---

pr_check.sh

With this change, the test runner should only execute `api_v1.test_ro` and `api_v2.test_ro`. See:
* Output of `pytest --help`, with focus on `-k` flag.
* https://github.com/RedHatInsights/cicd-tools/blob/main/cji_smoke_test.sh
* iqe-config-manager-plugin

ci: let PR check only run read-only API tests

---

.github/workflows/lint.yml
.golangci.yml

Set timeout to 2 minutes. Do it via config file.

ci: update golangci-lint timeout

---

internal/cmd/inventoryconsumer/cmd.go
internal/config/config.go

Inventory events older than the config value StaleEventDuration
(defaulting to 24 hours) are skipped. This should prevent flooding of
playbooks in the event config-manager stops processing messages from the
platform.inventory.events Kafka queue.
Fixes: ESSNTL-5271

feat: drop inventory events older than 24 hours

---

internal/cmd/inventoryconsumer/cmd.go
internal/db/types.go
internal/host.go
internal/http/v1/handlers.go

Temporarily revert 8e8065e2455e5ab0244f5cdefdf753608040e61d to allow testing of the stale event logic.
Refs: 8e8065e2455e5ab0244f5cdefdf753608040e61d

revert: access AccountID unsafely

---

Dockerfile

W.r.t  CVE-2023-44487 & CVE-2023-39325, respective packages may not be used here.
Team has decided to update the dependencies just in case.

feat: rebuild app image

---

infrastructure/persistence/cloudconnector/cloudconnector_test.go
infrastructure/persistence/dispatcher/dispatcher_test.go
infrastructure/persistence/inventory/inventory_repository_test.go
internal/http/v2/handlers_test.go

`httptest.NewServer` is commonly preferred for testing HTTP servers and clients in Go, without the need to bind to specific ports.
[reference](https://pkg.go.dev/net/http/httptest#Server)

RHINENG-8490 fix unit tests issue

---

deploy/clowdapp.yml

Getting below error in stage. 
```
{"level":"trace","http_client":"cloud-connector","method":"GET","url":"http://cloud-connector.cloud-connector-stage.svc.cluster.local:8080/api/cloud-connector/v2/v2/connections/5495e7b6-767a-4a96-a169-3c6937/status","headers":{"http_status":"Not Found","headers":{"Content-Length":["19"],"Content-Type":["text/plain; charset=utf-8"],"Date":["Tue, 19 Mar 2024 10:15:22 GMT"],"X-Content-Type-Options":["nosniff"]},"response":"404 page not found\n","time":"2024-03-19T10:15:22Z","caller":"/opt/app-root/src/infrastructure/persistence/cloudconnector/cloudconnector.go:119","message":"received HTTP response"}
{"level":"error","module":"inventory-consumer","offset":364160,"event_type":"updated","request_id":"7678ed7d-085d-40ee-9af4-201f4125e413","error":"unknown …
```

Fixes cloud-connector url

---

.github/pull_request_template.md
.github/workflows/lint.yml

`lint-commits` checks for every commit message of a PR to include `feat`, `fix`, and others which I think is not required. Also, not checking the commit message to include `RHINENG` with a GitHub action as it might be possible that there is no card for a minor fix and there is also a possibility that a card is from a different project. So, we need to add conditional checks for card no. in the commit message which is not possible. It is good to include Github pull_request_template.md file.

RHINENG-8911 add pull_request_template

---

infrastructure/persistence/inventory/inventory_repository.go
internal/dispatch/dispatch.go
internal/http/v2/handlers.go

Playbook was not getting dispatched on requesting POST /profiles. This was mainly because we are currently getting `401 Unauthorized` Status in the [response](https://github.com/RedHatInsights/config-manager/blob/master/infrastructure/persistence/inventory/inventory_repository.go#L85) due to missing `X-Rh-Identity` field in context.Context - we are sending [context.Background()](https://github.com/RedHatInsights/config-manager/blob/master/internal/dispatch/dispatch.go#L19) and we don't get any error i.e. the request was successfully sent, but the server responded with a 401 Unauthorized status. Due to this, it goes to [ApplyProfile](https://github.com/RedHatInsights/config-manager/blob/master/internal/dispatch/dispatch.go#L25) function with no hosts where it doesn't fall into any code …

RHINENG-5011 playbook not getting dispatched with POST /profiles

---

internal/playbook.go

Playbook tasks are being reordered every time we request GET /playbooks. The `Insights` playbook should be the first to be executed then the other services.

RHINENG-9142 Playbook tasks reorder on requesting GET /playbooks

---

Makefile
docs/dev-setup.md
scripts/run-event.json

To test our dispatcher-consumer service.

RHINENG-9025 add support to test playbook dispatcher run events in local

---

internal/config/config.go

Include `profile_id` param to v2/playbooks endpoint.

add profile_id param to /v2/playbooks endpoint

---

internal/cmd/inventoryconsumer/cmd.go
internal/host.go

Even though `RHCID` is the same as the `SubscriptionManagerID`, all (or most) hosts will have a SubscriptionManagerID even if they do not have a connection to Cloud Connector which can cause issues while getting connection status.

RHINENG-9355 RHCID should be used when calling GetConnectionStatus

---

.dockerignore

Ref-RHINENG-9414 create dockerignore file

---

internal/cmd/inventoryconsumer/cmd.go

We should try to process messages only when a host is connected via Cloud Connector i.e. `rhc_client_id` should be there else it would give us a connection status error.
```
{"level":"info","module":"inventory-consumer","offset":10,"event_type":"created","time":"2024-04-10T11:02:49+05:30","message":"setting up new host for remote host configuration"}
{"level":"trace","http_client":"cloud-connector","method":"GET","url":"http://127.0.0.1:8084/api/cloud-connector/v2/connections/4b1efbbe-a447-48d0-98c3-3594aae1d2c5/status","headers":{"X-Rh-Cloud-Connector-Client-Id":["suraj"],"X-Rh-Cloud-Connector-Org-Id":["0002"],"X-Rh-Cloud-Connector-Psk":["surajskey"],"X-Rh-Insights-Request-Id":["c1364858-e305-4e2e-b40a-0fcc86c37376"]},"time":"2024-04-10T11:02:49+05:30","caller":"/home/rohinichandra/Rohini …
```

RHINENG-8858 Skip cloud-connector connection attempt when RHCID is empty

---

internal/cmd/dispatcherconsumer/cmd.go
internal/cmd/httpapi/cmd.go
internal/cmd/inventoryconsumer/cmd.go

Remove logging statements for messages not relevant to the service's processing.
Below are the logs for messages which are not processed by config-manager.
```
{"level":"debug","config":{"AppName":"config-manager","AWSAccessKeyId":"...","AWSRegion":"us-east-1","AWSSecretAccessKey":"....","CloudConnectorClientID":"config-manager","CloudConnectorHost":{"Value":{"Scheme":"http","Opaque":"","User":null,"Host":"cloud-connector.cloud-connector-stage.svc.cluster.local:8080","Path":"/api/cloud-connector/","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"Text":"http://cloud-connector.cloud-connector-stage.svc.cluster.local:8080/api/cloud-connector/"},"CloudConnectorPSK":"8b58ec79f59cba06576dfecb","CloudConnectorTimeout":10,"DBHost":"config-manager-stag …
```

remove logging for messages not relevant to config-manager

---

internal/util/kafka.go

Facing this in Stage as empty Kafka CA cert testing was done in Stage yesterday. The current code checks if `KafkaCAPath` is there and then only configures Kafka reader and writer. 
```
{"level":"error","error":"fetching message: EOF","time":"2024-04-25T07:48:47Z","caller":"/opt/app-root/src/internal/cmd/dispatcherconsumer/cmd.go:28","message":"unable to read message"}
{"level":"error","error":"fetching message: EOF","time":"2024-04-25T07:49:02Z","caller":"/opt/app-root/src/internal/cmd/dispatcherconsumer/cmd.go:28","message":"unable to read message"}
{"level":"error","error":"fetching message: EOF","time":"2024-04-25T07:49:17Z","caller":"/opt/app-root/src/internal/cmd/dispatcherconsumer/cmd.go:28","message":"unable to read message"}
```
Feel free to add any other relevant details such as …

RHINENG-9694 Remove KafkaCAPath check

---

infrastructure/persistence/cloudconnector/cloudconnector.go

We are logging PSK values for Cloud Connector. We should avoid logging such info.

RHINENG-9596 do not log sensitive info

---

infrastructure/persistence/cloudconnector/cloudconnector.go

Updating `x-rh-cloud-connector-psk` to `X-Rh-Cloud-Connector-Psk` while excluding it from logs as I noticed in the logs that the latter is being used even though we have the former one in the code.

Ref-RHINENG-9596 Modify sensitiveField

---

infrastructure/persistence/cloudconnector/cloudconnector.go

Exclude PSK values logging from GetConnectionStatus function.

Ref-RHINENG-9596 Exclude PSK values logging from GetConnectionStatus

---

infrastructure/persistence/cloudconnector/cloudconnector.go

Remove redundancy by extracting out the duplicate codes in a function.

code refactor for filter headers

---

internal/http/v1/handlers.go
internal/http/v1/handlers_test.go

Getting 504 status code. Even though a resource is created (`newProfile`), the service may be experiencing delays in retrieving inventory clients from an external service. Therefore, it could result in timeouts.

RHINENG-9923 API v1 POST calls produce HTTP 504 responses

---

deploy/clowdapp.yml

As a part of the onboarding process, the deployment must have replicas >= 3.

RHINENG-10326 set replica pod count to 3

---

deploy/clowdapp.yml
pr_check.sh
scripts/bonfire.yml
scripts/docker-compose.yml

Recently, Cloud Connector has updated its component name from `cloud-connector-api` to `cloud-connector`. We need to update it on our end as well.
Reference - [MR](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/113709)

RHINENG-12143 update Cloud Connector component

---

internal/db/db_test.go
internal/http/v2/handlers_test.go

`rand.Seed()` has been deprecated since Go 1.20. The recommended approach now is to create a new random generator instance using `rand.New(rand.NewSource(seed))` if you need a specific sequence or use `rand.NewSource(seed)` directly for generating random numbers without modifying the global generator.

RHINENG-12161 Fix rand.Seed

---

deploy/clowdapp.yml

[ADR-046](https://docs.google.com/document/d/1yQNNqtgnowhrCXlnVM-vY-dvD4Woo__COSdcbzreyX8/edit)

RHINENG-11579 rename cpu/memory parameters and adjust values

---

deploy/clowdapp.yml

Use the new image created by Konflux.

RHINENG-12231 update quay repo reference to use new Konflux image

---

renovate.json

Konflux will send PRs every time something is updated - if we don't want these showing up randomly, we can actually configure this to batch changes!

RHINENG-12621 configure Renovate to batch Konflux changes to a particular day

---

Dockerfile

Migrate to UBI9 image. Jira card for this activity is RHINENG-12540.
I tested building of the image locally with:
```
podman build . -f ./Dockerfile -t test_build_config_manager
```
We need to migrate to newer image - UBI9.
- [ x] No

Migrate from UBI8 to UBI9

---

scripts/docker-compose.yml

related to https://issues.redhat.com/browse/RHINENG-16029
helps to avoid conflicts e.g. when running alongside kessel

make it possible to override the db port in docker-compose.yml

---

deploy/clowdapp.yml

As a part of service rescope, we are removing the dispatcher-consumer service from RHC-Manager.

RHINENG-18643 remove dispatcher-consumer deployment from clowdapp file
