api/controllers/config_manager_controller.go
application/config_manager_service.go
config/config.go
deploy/clowdapp.yml
domain/dispatcher.go
go.mod
go.sum
infrastructure/container.go
infrastructure/persistence/client_list_repository.go
infrastructure/persistence/dispatcher_repository.go
infrastructure/persistence/dispatcher_repository_test.go

Adding a connector for the playbook dispatcher. I haven't decided what to do with the results from the dispatcher yet. Currently they're just going to be logged (the user should still be able to update their state even if the hosts aren't able to be updated).

Implement playbook dispatcher connector

---

docker-compose.yml

Change `CM_DBHOST` to `CM_DB_HOST`.

Fix environment variable name

---

api/controllers/config_manager_controller.go

@dehort Here is the workaround we talked about. If insights is currently disabled then retrieve the clients from cloud-connector. Otherwise continue to use inventory. 
This is a temporary fix, but it doesn't solve the problem of knowing if a system is "up to date" when insights is disabled. We will most likely need to store state somewhere else.

Check insights status before getting clients

---

playbooks/compliance_openscap_remove.yml
playbooks/compliance_openscap_setup.yml

Depends on https://github.com/RedHatInsights/config-manager/pull/53

Update Compliance playbook comments

---

api/controllers/config_manager_controller.go
api/instrumentation/probes.go
api/main.go
cmd/run.go
go.sum

Some basic metrics around the api endpoints. Would like to add additional logging to instrumentation as a follow up.

Adding basic metrics to api endpoints

---

api/controllers/config_manager_controller.go
utils/utils.go
utils/utils_test.go

Fix for https://issues.redhat.com/browse/RHCLOUD-14374

idempotent state updates Ok

---

dashboards/grafana-dashboard-insights-config-manager-general.configmap.yaml

Very simple dashboard with some initial metrics

Adding initial dashboard

---

pr_check.sh

See: https://github.com/RedHatInsights/bonfire/pull/98

Make IQE_MARKER_EXPRESSION readonly

---

deploy/clowdapp.yml

https://github.com/RedHatInsights/clowder/pull/537/files

web: True is deprecated, webServices is current

---

api/controllers/config_manager_controller.go
api/main.go
application/config_manager_service.go
cmd/run.go
config/config.go
dispatcher-consumer/handler.go
dispatcher-consumer/main.go
domain/account_state.go
domain/cloud_connector.go
domain/inventory.go
domain/message/dispatcher.go
domain/message/inventory.go
domain/state_archive.go
infrastructure/container.go
infrastructure/kafka/kafka.go
infrastructure/persistence/account_state_repository.go
infrastructure/persistence/cloud_connector_repository.go
infrastructure/persistence/dispatcher/dispatcher.go
infrastructure/persistence/inventory_repository.go
infrastructure/persistence/state_archive_repository.go
inventory-consumer/handler.go
inventory-consumer/main.go
utils/http_client.go
utils/insights_sort.go
utils/utils.go

Add header documentation to a lot of application types, methods and
package functions.
Signed-off-by: Link Dupont <link@sub-pop.net>

docs: document most types, functions and methods

---

application/config_manager_service.go
application/generator_test.go
config/config.go
infrastructure/persistence/inventory_repository.go
infrastructure/persistence/inventory_repository_test.go
main.go

Minor changes to fix the linter warnings and fix a few failing tests.

fix linting and tests

---

infrastructure/persistence/cloudconnector/cloudconnector.go

Add a request-id header to each request created by the cloud-connector
API client. Additionally, add logging to each implemented method for
better log tracing.

refactor(log): add request-id to cloud-connector

---

go.mod
go.sum
utils/insights_sort_test.go
utils/utils_test.go

Refactor a couple tests to remove the gotest.tools package from the dependencies.

Drop gotest.tools

---

internal/http/v1/handlers.go
internal/http/v1/handlers_test.go
internal/http/v1/router.go

Include a route handler for POST /manage.
Fixes: ESSNTL-3222

fix(http): include POST /manage route

---

internal/config/config.go
internal/util/kafka.go

Load Kafka topics from Clowder.

Clowder Kafka topics

---

playbooks/insights_setup.yml

See commit messages for details. Fix [ESSNTL-3798](https://issues.redhat.com/browse/ESSNTL-3798).

Fix insights_setup.yml

---

build_deploy.sh

Please title this PR with a summary of the change, along with the JIRA card number.
Suggested formats: 
1. Fixes/Refs RHINENG-XXX - Title
2. RHINENG-XXX Title 
Feel free to remove this section from PR description once done.
Please include the __context of this change__ here.

RHINENG-9414 use tmp dir for docker config

---

internal/config/config.go
internal/util/kafka.go

Getting Kafka read issues locally even though I fixed it on stage - #165. 

RHINENG-9945 fix kafka read issue

---

dashboards/grafana-dashboard-insights-config-manager-general.configmap.yaml

Included as a part of the onboarding process.

RHINENG-10562 Create Grafana panels for chosen SLIs: availability and latency

---

dashboards/grafana-dashboard-insights-config-manager-general.configmap.yaml

RHINENG-10562 Add ConfigMap kind to grafana config

---

scripts/run-event.json

For testing [RHINENG-10432](https://issues.redhat.com/browse/RHINENG-10432)

update playbooks' url in run-events.json file

---

internal/http/v2/handlers.go

The application should always have at least one profile present i.e. the default state map.

RHINENG-10895 The app should have at least one profile present

---

.gitignore

For testing the Konflux pipeline.

Testing Konflux Pipeline

---

internal/config/config.go

do not depend on DefaultConfig.KesselEnabled as that is not available at this stage
Please title this PR with a summary of the change, along with the JIRA card number.
Suggested formats: 
1. Fixes/Refs RHINENG-XXX - Title
2. RHINENG-XXX Title 
Feel free to remove this section from PR description once done.
Please include the __context of this change__ here.

fix how RBAC dependency is resolved from Clowder
